lab7/myimgur/app/urls.py
from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:image_id>/', views.detail, name='detail'),
    path('<int:image_id>/comment', views.comment, name='comment'),
    path('<int:image_id>/upvote', views.upvote, name='upvote'),
    path('<int:image_id>/downvote', views.downvote, name='downvote'),
    path('new', views.create_image, name="create_image"),
    path('<int:image_id>/edit', views.update_image, name="edit_image"),
    path('<int:image_id>/delete', views.delete_image, name ="delete_image"),
    path('<int:comment_id>/approve', views.approve, name='approve'),
    path('<int:image_id>/like_comment/<int:comment_id>', views.liked, name = 'like'),
   
]

lab7/myimgur/imgur/urls.py
from django.contrib import admin
from django.urls import include,path
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('images/', include('app.urls')),
    path('', views.index, name='index'), 
    path('accounts/<user_id>', views.profile, name='profile'), 
]

lab7/myimgur/app/templates/includes/bs4_form.html
{% load widget_tweaks %}

 {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
  {% endfor %}

  {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
  {% endif %}

  {% for field in form.visible_fields %}
  <div class=" row form-group ">
    <div class="col-md-8 controls mx-auto">
      {{ field.label_tag }}

      {% if form.is_bound %}
        {% if field.errors %}
          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% else %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
        {% render_field field class="form-control" %}
      {% endif %}

      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
    </div>
  {% endfor %}

lab7/myimgur/app/templates/includes/delete_image_link.html
 <a href="#" id="delete_{{image.id}}" >Delete</a> 
<form action="{% url 'app:delete_image' image.id %}" method="post" id="delete_form_{{image.id}}"
 class="hidden">
{% csrf_token %}
</form>
<script charset="utf-8">
$(document).on('click', '#delete_{{image.id}}', function(){
$('#delete_form_{{ image.id }}').submit();
});
</script>

lab7/myimgur/app/templates/includes/image_list.html
{% for image,vote in images_with_votes %}
        <div class="row">
          <div class="col-md-2">
            <img class="app-fit" src="{{image.url}}" alt=""/>
          </div>
          <div class="col-md-10">
            <div class="date">
              <p class="red">
                
              Published: {{ image.pub_date }};  Comments: {{ image.comment_set.count }}
              {% if image.user.id == user.id or user.is_superuser%}
              <a href="{% url 'app:edit_image' image.id %}" >Edit</a>  | {% include "includes/delete_image_link.html" with image=image %}
              {% endif %}
              </p>
            </div>

              {% include "includes/vote_buttons.html" with image=image vote=vote%}
            <h2><a href="{% url 'app:detail' image.id %}">{{ image.title }}</a></h2>
            <p>{{ image.description|linebreaksbr }}</p>
            <p>Posted by {{ image.user }}</p>
          </div>
        </div>
    {% endfor %}

lab7/myimgur/app/templates/includes/vote_buttons.html
<div>
        <form action=" {% url 'app:upvote' image.id %}"
        method="post"
        role="form"
        class="form-inline float-left">
        {% csrf_token %}
        <input  type="submit" 
                value="+" 
                class="btn {{vote.upvote|yesno:'btn-success,'}}" />
        </form>

        <span class="vote-score float-left">{{image.vote_score}}</span>

        <form action=" {% url 'app:downvote'  image.id %}"
        method="post"
        role="form"
        class="form-inline float-left">
        {% csrf_token %}
        <input type="submit" value="-" 
        class="btn {{vote.downvote|yesno:'btn-danger,'}}" />
        </form>
</div>